### ISSUE TITLE
Make some players untrackable?

### ISSUE THREAD

**Issue by taucannonfox** [RedSparr0w/player_tracker#3]
I'm running a game datapack alongside this one where people automatically turn into spectators when they die, but they still show up in the compass interface and count as "nearest player" for that option as well. Is there a way to get the compass to not track certain people, or specifically just spectators, or something like that? If not, I think that would be a good feature to add.

**Comment by RedSparr0w** [comment]
Ah, yeah I didn't account for it tracking spectators, i'll try update it to support that.
